language: go
go:
- 1.7
before_deploy: go run caddy-downloader.go ${TRAVIS_TAG}
deploy:
  provider: releases
  api_key:
    secure: qSsoy4jjYDvhQrbZI1onm+NvAga8OQFTIYebjiD/iizN/VaVYa8Wr4hVMB9Jn9Hnt1FQdVgjiNbLk6N/oxTnZogP7nNkpCAzHu6taCOVmS4DPoNNl0p5DWWy/EtPUzGhwU1dehlGy4ffnVjXeySkhYykylNadnChNAkJZkaVM8t98Ixcpk8AXHcjm/XJMPrZdgcuDuu/ou/fm7fTo1VadQ5KcsQ4fy7Kg0t9C24nvoAEnxh5XOXxVCHu76U8ge8dLYNlW4t6yYJDG1yD2AU+wVrIR9zCPv9LrYd2aNrUhzxaoewDGj72qoQhjbnXzHWfF9+azBkVduXv+FOZihbJ7Xd3jOPfiPc3xTTsm+pvfwgoqx6H5CX/xrzqIf+74Pc92s3HAAU41sXu7wLFlFBm2lU/ckmhhndztljQ513bdKT6x4HY/xYraDp0vhCPBIGN7rpfwANzvO7fh+n9mtixCEMnvu6/Z+4mOP7zD1knJ3pCGcuJx1iyAhHHv5k+B+nn0tWRLnyCnYf/IhaQe063PopU+CFacrKeWbUEsEmwcfHopv53GHjVZ0WdRhOue7+nyYLdCiuKPyTpml2CQl9+CvD3iteHFOJCKfHlIZaz29ASdLwhb5g1NtIk9moghaJ0EmtUgt/I9f/e1tZNRMLHjCR8xef0jNE3KydLyfPx9G4=
  file: caddy-full-bin-${TRAVIS_TAG}-*.tar.gz
  on:
    tags: true
